import { isEnumValue } from '@gamepark/rules-api'

export enum AnimalCard {
  BearFox1 = 121,
  BearFox3 = 123,
  BearFox4 = 124,
  BearFox5 = 125,
  BearMoose1 = 131,
  BearMoose2 = 132,
  BearMoose4 = 134,
  BearMoose5 = 135,
  BearOrca1 = 141,
  BearOrca2 = 142,
  BearOrca3 = 143,
  BearOrca4 = 144,
  BearPuffin2 = 152,
  BearPuffin3 = 153,
  BearPuffin4 = 154,
  BearPuffin5 = 155,
  BearWalrus1 = 161,
  BearWalrus2 = 162,
  BearWalrus3 = 163,
  BearWalrus5 = 165,
  FoxBear2 = 212,
  FoxBear3 = 213,
  FoxBear4 = 214,
  FoxBear5 = 215,
  FoxMoose1 = 231,
  FoxMoose3 = 233,
  FoxMoose4 = 234,
  FoxMoose5 = 235,
  FoxOrca1 ,
  FoxOrca2 ,
  FoxOrca3 ,
  FoxOrca5 ,
  FoxPuffin1 ,
  FoxPuffin2 ,
  FoxPuffin3 ,
  FoxPuffin4 ,
  FoxWalrus1 ,
  FoxWalrus2 ,
  FoxWalrus4 ,
  FoxWalrus5 ,
  MooseBear1 ,
  MooseBear2 ,
  MooseBear3 ,
  MooseBear4 ,
  MooseFox2 ,
  MooseFox3 ,
  MooseFox4 ,
  MooseFox5 ,
  MooseOrca1 ,
  MooseOrca2 ,
  MooseOrca4 ,
  MooseOrca5 ,
  MoosePuffin1 ,
  MoosePuffin2 ,
  MoosePuffin3 ,
  MoosePuffin5 ,
  MooseWalrus1 ,
  MooseWalrus3 ,
  MooseWalrus4 ,
  MooseWalrus5 ,
  OrcaBear1 ,
  OrcaBear2 ,
  OrcaBear4 ,
  OrcaBear5 ,
  OrcaFox1 ,
  OrcaFox2 ,
  OrcaFox3 ,
  OrcaFox5 ,
  OrcaMoose1 ,
  OrcaMoose2 ,
  OrcaMoose3 ,
  OrcaMoose4 ,
  OrcaPuffin1 ,
  OrcaPuffin3 ,
  OrcaPuffin4 ,
  OrcaPuffin5 ,
  OrcaWalrus2 ,
  OrcaWalrus3 ,
  OrcaWalrus4 ,
  OrcaWalrus5 ,
  PuffinBear1 ,
  PuffinBear3 ,
  PuffinBear4 ,
  PuffinBear5 ,
  PuffinFox1 ,
  PuffinFox2 ,
  PuffinFox4 ,
  PuffinFox5 ,
  PuffinMoose1 ,
  PuffinMoose2 ,
  PuffinMoose3 ,
  PuffinMoose5 ,
  PuffinOrca2 ,
  PuffinOrca3 ,
  PuffinOrca4 ,
  PuffinOrca5 ,
  PuffinWalrus1 ,
  PuffinWalrus2 ,
  PuffinWalrus3 ,
  PuffinWalrus4 ,
  WalrusBear1 ,
  WalrusBear2 ,
  WalrusBear3 ,
  WalrusBear5 ,
  WalrusFox1 ,
  WalrusFox2 ,
  WalrusFox3 ,
  WalrusFox4 ,
  WalrusMoose2 ,
  WalrusMoose3 ,
  WalrusMoose4 ,
  WalrusMoose5 ,
  WalrusOrca1 ,
  WalrusOrca3 ,
  WalrusOrca4 ,
  WalrusOrca5 ,
  WalrusPuffin1 ,
  WalrusPuffin2 ,
  WalrusPuffin4 ,
  WalrusPuffin5 ,
}

export const animalCards = Object.values(AnimalCard).filter(isEnumValue)